(() => {
  const $ = (selector, root = document) => root.querySelector(selector);
  const $$ = (selector, root = document) => [...root.querySelectorAll(selector)];
  const handling = {
    preset: { balanced: [1500, 32, 0.78, 8.5, 2.1, 0.28], street: [1450, 27, 0.68, 7, 1.8, 0.24], drift: [1350, 42, 0.62, 5.5, 2.8, 0.18], offroad: [1700, 24, 0.58, 6.5, 1.6, 0.42] },
    flags: { AWD: 0, bulletproof: 1, armour: 2, offroad: 4, openwheel: 8, indestructible: 16 }
  };
  let latestHandling = null;
  const read = (id) => $("#" + id)?.value ?? "";
  const checked = (id) => $("#" + id)?.checked;
  const output = (text) => { $("#tool-output").hidden = false; $("#tool-output").innerHTML = `<code>${text.replace(/[&<>]/g, (c) => ({"&":"&amp;","<":"&lt;",">":"&gt;"}[c]))}</code>`; };
  const download = (name, text) => { const a = document.createElement("a"); a.href = URL.createObjectURL(new Blob([text], { type: "text/plain" })); a.download = name; a.click(); URL.revokeObjectURL(a.href); };
  const flagsValue = () => Object.entries(handling.flags).reduce((sum, [id, bit]) => sum + (checked(`flag-${id}`) ? 1 << bit : 0), 0).toString(16).toUpperCase().padStart(8, "0");
  const makeHandling = () => {
    const name = read("vehicle-name").trim().toLowerCase().replace(/[^a-z0-9_]/g, "_") || "gankbyte_vehicle";
    const weight = Number(read("vehicle-weight")) || 1500;
    const power = Number(read("vehicle-power")) || 32;
    const traction = Number(read("vehicle-traction")) || .78;
    const brake = Number(read("vehicle-brake")) || 8.5;
    const drive = Number(read("vehicle-drive")) || 2.1;
    const suspension = Number(read("vehicle-suspension")) || .28;
    const meta = `<CHandlingDataMgr>\n  <HandlingData>\n    <Item>\n      <handlingName>${name.toUpperCase()}</handlingName>\n      <fMass value="${weight.toFixed(2)}" />\n      <fInitialDriveForce value="${(power / 100).toFixed(3)}" />\n      <fClutchChangeRateScaleUpShift value="${drive.toFixed(2)}" />\n      <fClutchChangeRateScaleDownShift value="${drive.toFixed(2)}" />\n      <fBrakeForce value="${brake.toFixed(2)}" />\n      <fTractionCurveMax value="${traction.toFixed(2)}" />\n      <fTractionCurveMin value="${Math.max(.1, traction - .12).toFixed(2)}" />\n      <fSuspensionForce value="${suspension.toFixed(2)}" />\n      <strHandlingFlags>${flagsValue()}</strHandlingFlags>\n    </Item>\n  </HandlingData>\n</CHandlingDataMgr>`;
    const lua = `-- Generated by GankByte FiveM Tools\nlocal handlingName = '${name.toUpperCase()}'\n\nCreateThread(function()\n    local vehicle = GetVehiclePedIsIn(PlayerPedId(), false)\n    if vehicle ~= 0 then\n        SetVehicleHandlingFloat(vehicle, 'CHandlingData', 'fInitialDriveForce', ${(power / 100).toFixed(3)})\n        SetVehicleHandlingFloat(vehicle, 'CHandlingData', 'fBrakeForce', ${brake.toFixed(2)})\n        SetVehicleHandlingFloat(vehicle, 'CHandlingData', 'fTractionCurveMax', ${traction.toFixed(2)})\n    end\nend)`;
    latestHandling = { name, text: `handling.meta\n${meta}\n\nclient.lua\n${lua}` };
    output(latestHandling.text);
  };
  const applyPreset = () => { const values = handling.preset[read("handling-preset")] || handling.preset.balanced; ["vehicle-weight", "vehicle-power", "vehicle-traction", "vehicle-brake", "vehicle-drive", "vehicle-suspension"].forEach((id, i) => { $("#" + id).value = values[i]; }); };
  const generateIdea = () => {
    const category = read("script-category"), framework = read("script-framework"), complexity = read("script-complexity"), focus = read("script-focus"), requirements = read("script-requirements").trim() || "Keep the first release small and easy to test.";
    const title = `${category} ${focus}`;
    const files = complexity === "starter" ? ["fxmanifest.lua", "config.lua", "client/main.lua", "README.md"] : ["fxmanifest.lua", "config.lua", "client/main.lua", "server/main.lua", "shared/utils.lua", "README.md", "LICENSE"];
    $("#script-output").hidden = false;
    $("#script-output").innerHTML = `<div class="generated-plan"><article><h3>${title}</h3><p>Framework: ${framework} · Scope: ${complexity}</p><p>${requirements}</p></article><article><h3>Build plan</h3><ul><li>Define the player-facing command, event, or interaction.</li><li>Keep client and server responsibilities separate.</li><li>Validate permissions and input on the server.</li><li>Add a config file instead of hard-coding server choices.</li><li>Document installation, dependencies, exports, and known limits.</li></ul></article><article><h3>Suggested files</h3><ul>${files.map((file) => `<li><code>${file}</code></li>`).join("")}</ul></article></div>`;
  };
  $$(".tool-tab").forEach((tab) => tab.addEventListener("click", () => { $$(".tool-tab").forEach((item) => item.setAttribute("aria-selected", String(item === tab))); $$(".tool-pane").forEach((pane) => pane.classList.toggle("active", pane.id === tab.dataset.target)); }));
  $("#handling-preset")?.addEventListener("change", applyPreset);
  $("#generate-handling")?.addEventListener("click", makeHandling);
  $("#download-handling")?.addEventListener("click", () => { if (!latestHandling) makeHandling(); download(`${latestHandling.name}-handling.txt`, latestHandling.text); });
  $("#generate-script")?.addEventListener("click", generateIdea);
})();
