(() => {
  "use strict";
  const $ = (id) => document.getElementById(id), input = $("health-files"), status = $("health-status"), report = $("health-report"), guidance = $("health-guidance"); let currentReport = "Load a project to create a report.";
  const pathOf = (file) => (file.webkitRelativePath || file.name).replaceAll("\\", "/");
  const readFiles = async () => Promise.all([...input.files].map(async (file) => ({ path: pathOf(file), size: file.size, text: /\.(lua|luau|py|js|jsx|ts|tsx|java|kt|sql|json|ya?ml|toml|ini|cfg|properties|xml|html?|css|scss|md|txt|meta|gradle|kts)$/i.test(file.name) && file.size < 2_000_000 ? await file.text() : "" })));
  const exists = (files, regex) => files.some((file) => regex.test(file.path));
  function scan(files) { const paths = files.map((file) => file.path.toLowerCase()), all = files.map((file) => file.text).join("\n"), findings = []; const add = (kind, title, detail) => findings.push({kind,title,detail}); const type = exists(files, /(^|\/)fxmanifest\.lua$|(^|\/)__resource\.lua$/) ? "FiveM" : exists(files, /(^|\/)server\.properties$|(^|\/)plugin\.yml$|(^|\/)fabric\.mod\.json$/) ? "Minecraft" : exists(files, /(^|\/)(pom\.xml|build\.gradle|build\.gradle\.kts)$/) ? "Java" : exists(files, /(^|\/)(package\.json|tsconfig\.json)$/) ? "JavaScript / TypeScript" : exists(files, /\.py$/) ? "Python" : exists(files, /\.lua$/) ? "Lua" : "General"; const readme = exists(files, /(^|\/)readme(\.md|\.txt)?$/i), licence = exists(files, /(^|\/)(license|licence)(\..*)?$/i), tests = paths.some((p) => /(^|\/)(test|tests|spec|__tests__)(\/|\.)/.test(p) || /(^|\/)(package\.json|pyproject\.toml|build\.gradle)/.test(p) && all.includes("test")); if (readme) add("good","README found","Installation and usage can be documented for the next person."); else add("error","README is missing","Add setup, dependencies, configuration, usage, and troubleshooting instructions."); if (licence) add("good","Licence found","The project states how it may be used or shared."); else add("warn","Licence is missing","Add a licence before publishing source or distributing a resource."); if (tests) add("good","Test signal found","A test folder or test configuration was detected."); else add("warn","No test signal found","Add at least one repeatable check or explain how the project is verified."); const secretFiles = paths.filter((p) => /(^|\/)(\.env(?:\..*)?|id_rsa|credentials\.json|secrets?\.(json|ya?ml)|.*\.(pem|key|p12|pfx))$/i.test(p)); if (secretFiles.length) add("error","Possible secrets found",secretFiles.slice(0,5).join(", ")); else add("good","No obvious secret files","Common private-key and environment-secret filenames were not detected."); if (type === "FiveM") { add(exists(files, /(^|\/)fxmanifest\.lua$/) ? "good" : "warn","FiveM manifest",exists(files, /(^|\/)fxmanifest\.lua$/) ? "fxmanifest.lua is present." : "Legacy or missing manifest; add fxmanifest.lua."); } if (type === "Minecraft") add(exists(files, /(^|\/)eula\.txt$/) ? "good" : "warn","Minecraft EULA",exists(files, /(^|\/)eula\.txt$/) ? "EULA file is present." : "Document the EULA choice for server deployment."); const suspicious = paths.filter((p) => p.startsWith("/") || p.includes("../") || /(^|\/)[a-z]:[\\/]/i.test(p)); if (suspicious.length) add("warn","Suspicious paths",suspicious.slice(0,5).join(", ")); if (!findings.length) add("good","No findings","The project did not trigger the basic checks."); const errors = findings.filter((f) => f.kind === "error").length, warns = findings.filter((f) => f.kind === "warn").length, score = Math.max(0, Math.round(100 - errors * 25 - warns * 10)); return {type, score, errors, findings}; }
  function render(result, count) { $("health-score").textContent = `${result.score}/100`; $("health-type").textContent = result.type; $("health-count").textContent = count; $("health-errors").textContent = result.errors; guidance.replaceChildren(...result.findings.map((item) => { const li = document.createElement("li"); li.className = item.kind; li.innerHTML = `<strong>${item.title}</strong> - ${item.detail}`; return li; })); currentReport = [`GankByte Project Health Report`, `Type: ${result.type}`, `Score: ${result.score}/100`, `Files: ${count}`, `Errors: ${result.errors}`, "", ...result.findings.map((item) => `${item.kind.toUpperCase()}: ${item.title} - ${item.detail}`)].join("\n"); report.textContent = currentReport; }
  $("scan-health").addEventListener("click", async () => { if (!input.files.length) { status.textContent = "Choose a project folder or files first."; status.classList.add("is-error"); return; } status.textContent = "Reading files locally..."; status.classList.remove("is-error"); try { const files = await readFiles(); const result = scan(files); render(result, files.length); status.textContent = `Scanned ${files.length} file${files.length === 1 ? "" : "s"} locally.`; } catch (error) { status.textContent = `Could not read the project: ${error.message}`; status.classList.add("is-error"); } });
  $("clear-health").addEventListener("click", () => { input.value = ""; currentReport = "Load a project to create a report."; report.textContent = currentReport; guidance.innerHTML = "<li>Checks will appear after a scan.</li>"; $("health-score").textContent = $("health-type").textContent = $("health-count").textContent = $("health-errors").textContent = "-"; status.textContent = "Project cleared."; });
  $("copy-health").addEventListener("click", async () => { try { await navigator.clipboard.writeText(currentReport); status.textContent = "Report copied to the clipboard."; } catch { status.textContent = "Clipboard access was unavailable."; status.classList.add("is-error"); } });
  $("download-health").addEventListener("click", () => { const url = URL.createObjectURL(new Blob([currentReport], {type:"text/plain;charset=utf-8"})); const link = document.createElement("a"); link.href = url; link.download = "gankbyte-project-health.txt"; link.click(); URL.revokeObjectURL(url); status.textContent = "Report downloaded."; });
})();
