(() => {
  "use strict";

  const $ = (id) => document.getElementById(id);
  const canvas = $("signal-canvas");
  const ctx = canvas.getContext("2d");
  const config = window.GANKBYTE_XP_CONFIG || {};
  const W = canvas.width;
  const H = canvas.height;
  const gravity = 760;
  const laneY = 450;
  const initialCharges = { redirect: 5, bridge: 3, cleanse: 3, pulse: 2, recall: 1, blocker: 3, floater: 3 };
  const abilityNames = { redirect: "REDIRECT", bridge: "BRIDGE", cleanse: "CLEANSE", pulse: "SIGNAL PULSE", recall: "EMERGENCY RECALL", blocker: "BLOCKER", floater: "FLOATER" };
  const speedNames = ["SAFE", "PUSH", "GANK"];
  const speedFactors = [0.72, 1, 1.3];
  const speedMultipliers = [0.8, 1.15, 1.6];
  const bestKey = "gankbyte-signal-swarm-best";
  const statsKey = "gankbyte-signal-swarm-stats";
  const achievementsKey = "gankbyte-signal-swarm-achievements";
  const platforms = [
    { x1: 25, x2: 240, y: 220 }, { x1: 270, x2: 465, y: 330 },
    { x1: 485, x2: 620, y: 430 }, { x1: 700, x2: 940, y: 430 }
  ];
  const exits = [{ x: 925, y: 450 }];

  let running = false, paused = false, finished = false, lastFrame = 0, elapsed = 0;
  let score = 0, saved = 0, lost = 0, combo = 1, bestCombo = 1, fastestRescue = null, speed = 0;
  let selectedAbility = "redirect", charges = { ...initialCharges }, signals = [], hazards = [], corruption = [], powerups = [], bridges = [], particles = [];
  let pulseUntil = 0, freezeUntil = 0, doubleUntil = 0, safeRouteUntil = 0, echoUntil = 0, nextSpawn = 0, nextHazard = 3, nextCorruption = 3, nextPowerup = 8;
  let target = { x: 300, y: laneY }, selectedSignalId = null, client = null, user = null, lastRun = null;
  let pointerStart = null, pointerMoved = false, viewOffset = { x: 0, y: 0 };

  const random = (min, max) => Math.random() * (max - min) + min;
  const clamp = (value, min, max) => Math.max(min, Math.min(max, value));
  const format = (value) => Number(value || 0).toLocaleString();
  const distance = (a, b) => Math.hypot(a.x - b.x, a.y - b.y);
  const escapeHtml = (value) => String(value || "").replace(/[&<>'"]/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", '"': "&quot;" }[character]));

  function localStats() { try { return JSON.parse(localStorage.getItem(statsKey) || "null") || { runs: 0, saved: 0, perfect: 0, bestCombo: 1 }; } catch { return { runs: 0, saved: 0, perfect: 0, bestCombo: 1 }; } }
  function achievement(name) { let list = []; try { list = JSON.parse(localStorage.getItem(achievementsKey) || "[]"); } catch { list = []; } if (!list.includes(name)) list.push(name); localStorage.setItem(achievementsKey, JSON.stringify(list)); }
  function burst(x, y, color, amount = 16) { for (let i = 0; i < Math.min(amount, 12); i += 1) { const a = random(0, Math.PI * 2), force = random(20, 95); particles.push({ x, y, vx: Math.cos(a) * force, vy: Math.sin(a) * force, life: random(.25, .6), color, size: random(2, 4) }); } }
  function updateHud() {
    $("swarm-score").textContent = format(score); $("swarm-saved").textContent = saved; $("swarm-time").textContent = Math.ceil(Math.max(0, 60 - elapsed)); $("swarm-combo").textContent = `x${combo}`; $("swarm-lost").textContent = lost; $("swarm-phase").textContent = elapsed >= 45 ? "FINAL" : elapsed >= 30 ? "3" : elapsed >= 15 ? "2" : "1"; $("swarm-speed-label").textContent = speedNames[speed];
    $("swarm-power").textContent = pulseUntil > elapsed ? "PULSE" : doubleUntil > elapsed ? "DOUBLE" : freezeUntil > elapsed ? "FREEZE" : safeRouteUntil > elapsed ? "SAFE ROUTE" : "NONE";
    Object.keys(charges).forEach((name) => { const node = $(`charges-${name}`); node.textContent = charges[name]; node.closest(".signal-ability")?.classList.toggle("is-empty", charges[name] === 0); node.closest(".signal-ability")?.setAttribute("aria-label", `${abilityNames[name]}, ${charges[name]} charges`); });
  }
  function resetRun() {
    running = false; paused = false; finished = false; elapsed = 0; score = 0; saved = 0; lost = 0; combo = 1; bestCombo = 1; fastestRescue = null; speed = 0; charges = { ...initialCharges }; pulseUntil = 0; freezeUntil = 0; doubleUntil = 0; safeRouteUntil = 0; echoUntil = 0; nextSpawn = 0; nextHazard = 3; nextCorruption = 3; nextPowerup = 8; target = { x: 300, y: laneY }; signals = []; hazards = []; corruption = []; powerups = []; bridges = []; particles = []; viewOffset = { x: 0, y: 0 };
    $("signal-message").hidden = false; $("signal-message").innerHTML = "<strong>READY?</strong><span>Signals walk automatically. Place bridges, turn them around, and rescue as many as possible.</span>"; $("signal-collapse").classList.remove("show"); $("swarm-result").hidden = true; $("swarm-pause").hidden = true; $("swarm-restart").hidden = true; $("swarm-start").hidden = false; $("swarm-start").innerHTML = "Start run <span>&rarr;</span>"; $("swarm-speed").value = "0"; $("swarm-status").textContent = localStorage.getItem(bestKey) ? `Best score on this device: ${format(localStorage.getItem(bestKey))}.` : "Save the swarm or push the score. Your best run is saved on this device."; updateHud();
  }
  function createSignal() { const roll = Math.random(), type = roll < .2 ? "carrier" : roll < .44 ? "spark" : "runner"; signals.push({ id: `${elapsed}-${Math.random()}`, alive: true, x: 55, y: 70, vx: type === "runner" ? 72 : type === "carrier" ? 43 : 56, vy: 0, direction: 1, type, grounded: false, lastSafeX: 55, lastSafeY: 202, spawnTime: elapsed, phase: random(0, 7), repaired: false, pulseUntil: 0, shieldUntil: 0, blockedUntil: 0, floaterUntil: 0 }); }
  function supportAt(x, y) { const candidates = [...platforms, ...bridges.map((bridge) => ({ x1: bridge.x1, x2: bridge.x2, y: bridge.y }))]; return candidates.find((platform) => x >= platform.x1 - 5 && x <= platform.x2 + 5 && Math.abs(platform.y - (y + 18)) < 12) || null; }
  function landingAt(x, previousY, nextY) { const previousBottom = previousY + 18, nextBottom = nextY + 18; const candidates = [...platforms, ...bridges.map((bridge) => ({ x1: bridge.x1, x2: bridge.x2, y: bridge.y }))]; return candidates.find((platform) => x >= platform.x1 - 5 && x <= platform.x2 + 5 && previousBottom <= platform.y && nextBottom >= platform.y) || null; }
  function spawnHazard() { const base = platforms[Math.floor(random(0, 4))]; hazards.push({ x: random(base.x1 + 25, base.x2 - 25), y: base.y - 18, direction: Math.random() > .5 ? 1 : -1, speed: random(45, 85), radius: random(13, 19), phase: random(0, 7) }); }
  function spawnCorruption() { const base = platforms[Math.floor(random(0, 3))]; corruption.push({ x: random(base.x1 + 25, base.x2 - 25), y: base.y - 18, ttl: elapsed + random(12, 24), pulse: random(0, 7) }); }
  function spawnPowerup() { const base = platforms[Math.floor(random(0, platforms.length))]; powerups.push({ x: random(base.x1 + 20, base.x2 - 20), y: base.y - 25, type: ["clean", "freeze", "double", "safe", "echo"][Math.floor(random(0, 5))], ttl: elapsed + 15, pulse: random(0, 7) }); }
  function currentSpeed(signal) { return speedFactors[speed] * (pulseUntil > elapsed ? 1.35 : 1) * (signal?.pulseUntil > elapsed ? 1.35 : 1); }
  function currentMultiplier(signal) { return speedMultipliers[speed] * (pulseUntil > elapsed ? 1.25 : 1) * (signal?.pulseUntil > elapsed ? 1.25 : 1); }
  function boardPoint(event) { const rect = canvas.getBoundingClientRect(); return { x: clamp((event.clientX - rect.left) * W / rect.width - viewOffset.x, 0, W), y: clamp((event.clientY - rect.top) * H / rect.height - viewOffset.y, 0, H) }; }
  function nearestSignal(point, maxDistance = Infinity) { return signals.filter((signal) => signal.alive && distance(signal, point) <= maxDistance).sort((a, b) => distance(a, point) - distance(b, point))[0]; }
  function findGap(point) { return platforms.slice(0, -1).map((platform, index) => ({ x1: platform.x2, x2: platforms[index + 1].x1, y: Math.max(platform.y, platforms[index + 1].y) })).find((gap) => gap.x2 - gap.x1 > 12 && point.x >= gap.x1 - 45 && point.x <= gap.x2 + 45 && Math.abs(point.y - gap.y) < 90) || null; }
  function useAbility(name, point = target) {
    if (!running || paused || charges[name] <= 0) return;
    target = point; charges[name] -= 1;
    if (name === "redirect") { const signal = nearestSignal(point, 72); if (signal) { selectedSignalId = signal.id; signal.direction *= -1; signal.vx = Math.abs(signal.vx) * signal.direction; $("swarm-status").textContent = `${signal.type.toUpperCase()} turned around. Route it away from danger.`; burst(signal.x, signal.y, "#c6ff3d", 20); } else { charges[name] += 1; $("swarm-status").textContent = "Aim Redirect at a nearby Signal."; } }
    if (name === "bridge") { const gap = findGap(point); const hazard = hazards.find((item) => distance(item, point) < 75); if (gap) { const y = gap.y; bridges.push({ x1: gap.x1 - 8, x2: gap.x2 + 8, y, ttl: elapsed + 9 }); $("swarm-status").textContent = "Temporary bridge placed. Get the swarm across before it fades."; burst((gap.x1 + gap.x2) / 2, y, "#55e8ff", 24); } else if (hazard) { const x1 = clamp(hazard.x - 48, 20, W - 100), x2 = clamp(hazard.x + 48, 120, W - 20); bridges.push({ x1, x2, y: hazard.y, ttl: elapsed + 7 }); hazards = hazards.filter((item) => item !== hazard); $("swarm-status").textContent = "Bridge placed over the hazard. The route is safe for a few seconds."; burst(hazard.x, hazard.y, "#55e8ff", 24); } else { charges[name] += 1; $("swarm-status").textContent = "Aim Bridge at a gap or red hazard."; } }
    if (name === "cleanse") { const beforeZones = corruption.length, beforeHazards = hazards.length; corruption = corruption.filter((zone) => distance(zone, point) > 150); hazards = hazards.filter((item) => distance(item, point) > 140); const cleared = (beforeZones - corruption.length) + (beforeHazards - hazards.length); if (!cleared) charges[name] += 1; $("swarm-status").textContent = cleared ? `Cleansed ${cleared} danger${cleared === 1 ? "" : "s"}.` : "Aim Cleanse at a red hazard or corruption zone."; burst(point.x, point.y, "#c6ff3d", 28); }
    if (name === "pulse") { const signal = nearestSignal(point, 82); if (signal) { selectedSignalId = signal.id; signal.pulseUntil = Math.max(signal.pulseUntil, elapsed) + 6; $("swarm-status").textContent = `${signal.type.toUpperCase()} overclocked. Rescue it during the scoring window.`; burst(signal.x, signal.y, "#ffb347", 28); } else { pulseUntil = Math.max(pulseUntil, elapsed) + 6; $("swarm-status").textContent = "SIGNAL PULSE active for the whole swarm."; burst(point.x, point.y, "#ffb347", 28); } }
    if (name === "recall") { let count = 0; signals.forEach((signal) => { if (signal.alive && distance(signal, point) < 190) { signal.x = signal.lastSafeX; signal.y = signal.lastSafeY; signal.vy = 0; signal.grounded = true; signal.shieldUntil = elapsed + 3; count += 1; } }); if (!count) charges[name] += 1; else { combo = 1; score = Math.max(0, score - 120); } $("swarm-status").textContent = count ? `Emergency Recall returned ${count} Signal${count === 1 ? "" : "s"}. Score penalty applied.` : "Aim Recall at nearby Signals."; burst(point.x, point.y, "#ff4f68", 30); }
    if (name === "blocker") { const signal = nearestSignal(point, 72); if (signal) { selectedSignalId = signal.id; signal.blockedUntil = signal.blockedUntil > elapsed ? 0 : elapsed + 8; $("swarm-status").textContent = signal.blockedUntil > elapsed ? `${signal.type.toUpperCase()} is blocking the route. Following Signals will turn around.` : "Blocker released. The Signal is walking again."; burst(signal.x, signal.y, "#ff4f68", 22); } else { charges[name] += 1; $("swarm-status").textContent = "Aim Blocker at a nearby Signal."; } }
    if (name === "floater") { const signal = nearestSignal(point, 82); if (signal) { selectedSignalId = signal.id; signal.floaterUntil = Math.max(signal.floaterUntil, elapsed) + 10; $("swarm-status").textContent = `${signal.type.toUpperCase()} has a Floater. Safer drops for 10 seconds.`; burst(signal.x, signal.y, "#55e8ff", 22); } else { charges[name] += 1; $("swarm-status").textContent = "Aim Floater at a nearby Signal."; } }
    updateHud();
  }
  function lose(signal, reason) { if (!signal.alive) return; signal.alive = false; if (selectedSignalId === signal.id) selectedSignalId = null; lost += 1; combo = 1; score = Math.max(0, score - 30); burst(signal.x, signal.y, "#ff4f68", 18); $("swarm-status").textContent = reason || "Signal lost. Combo broken."; }
  function rescue(signal) { if (!signal.alive) return; signal.alive = false; if (selectedSignalId === signal.id) selectedSignalId = null; saved += 1; const base = signal.type === "carrier" ? 180 : signal.type === "spark" ? 95 : 65; combo = Math.min(10, combo + (signal.type === "carrier" ? 2 : 1)); bestCombo = Math.max(bestCombo, combo); const rescueTime = Math.max(0, elapsed - signal.spawnTime); fastestRescue = fastestRescue === null ? rescueTime : Math.min(fastestRescue, rescueTime); let gained = Math.round(base * combo * currentMultiplier(signal)); if (doubleUntil > elapsed) gained *= 2; if (echoUntil > elapsed) gained += 75; score += gained; $("swarm-status").textContent = signal.type === "carrier" && combo >= 5 ? `PERFECT RESCUE // +${format(gained)} // COMBO x${combo}` : `${signal.type.toUpperCase()} rescued // +${format(gained)} // COMBO x${combo}`; burst(signal.x, signal.y, signal.type === "carrier" ? "#ffb347" : "#c6ff3d", combo >= 5 ? 30 : 15); }
  function collectPowerup(power) { powerups = powerups.filter((item) => item !== power); if (power.type === "clean") { corruption.splice(0, Math.min(3, corruption.length)); $("swarm-status").textContent = "CLEAN SWEEP cleared the oldest corruption."; } if (power.type === "freeze") { freezeUntil = elapsed + 6; $("swarm-status").textContent = "TIME FREEZE stopped the moving hazard."; } if (power.type === "double") { doubleUntil = elapsed + 8; $("swarm-status").textContent = "DOUBLE SIGNAL is active. Rescue points doubled."; } if (power.type === "safe") { safeRouteUntil = elapsed + 9; $("swarm-status").textContent = "SAFE ROUTE marked the safest current platform."; } if (power.type === "echo") { echoUntil = elapsed + 8; $("swarm-status").textContent = "SWARM ECHO is active. Rescues carry bonus points."; } burst(power.x, power.y, "#55e8ff", 28); }
  function updateSignal(signal, dt) {
    if (!signal.alive) return;
    const factor = currentSpeed(signal);
    if (!signal.grounded) { const previousY = signal.y; signal.vy += gravity * (signal.floaterUntil > elapsed ? .24 : 1) * dt; signal.y += signal.vy * dt; if (signal.y > H + 30) { lose(signal, "A Signal fell through the network. Build a bridge or use Floater."); return; } const landing = signal.vy > 0 ? landingAt(signal.x, previousY, signal.y) : null; if (landing) { signal.y = landing.y - 18; signal.vy = 0; signal.grounded = true; signal.lastSafeX = signal.x; signal.lastSafeY = signal.y; } return; }
    if (signal.blockedUntil > elapsed) { signal.phase += dt * 2; return; }
    const blocker = signals.find((other) => other !== signal && other.alive && other.blockedUntil > elapsed && Math.abs(other.y - signal.y) < 16 && Math.abs(other.x - signal.x) < 30 && Math.sign(signal.vx) === Math.sign(other.x - signal.x));
    if (blocker) { signal.direction *= -1; signal.vx = Math.abs(signal.vx) * signal.direction; signal.phase += dt * 2; return; }
    const nextX = signal.x + signal.vx * factor * dt;
    const support = supportAt(nextX, signal.y);
    const current = supportAt(signal.x, signal.y);
    if (!support || Math.abs(support.y - (signal.y + 18)) > 14) { if (current && signal.direction < 0 && nextX < current.x1) { signal.direction = 1; signal.vx = Math.abs(signal.vx); signal.x = current.x1; return; } signal.grounded = false; signal.vy = 40; signal.x = nextX; return; }
    signal.x = nextX; signal.y = support.y - 18; signal.lastSafeX = signal.x; signal.lastSafeY = signal.y; signal.phase += dt * 6;
    if (signal.x < 18 || signal.x > W - 18) { signal.direction *= -1; signal.vx = Math.abs(signal.vx) * signal.direction; }
    if (signal.x >= 902 && signal.y > 410) { rescue(signal); return; }
    const zone = corruption.find((item) => distance(item, signal) < 24);
    if (!signal.shieldUntil || signal.shieldUntil <= elapsed) {
      if (zone && !(safeRouteUntil > elapsed && signal.y < 400)) { lose(signal, "Corruption blocked the platform. Redirect or cleanse it."); return; }
      const hazard = hazards.find((item) => distance(item, signal) < item.radius + 12);
      if (hazard) { lose(signal, "A moving hazard hit the platform. Redirect the swarm or use a power-up."); return; }
    }
    const power = powerups.find((item) => distance(item, signal) < 24); if (power) collectPowerup(power);
    if (signal.type === "spark" && !signal.repaired) { const sparkZone = corruption.find((item) => distance(item, signal) < 48); if (sparkZone) { sparkZone.ttl = Math.min(sparkZone.ttl, elapsed + 2); signal.repaired = true; burst(sparkZone.x, sparkZone.y, "#55e8ff", 14); } }
    if (current && support && current.y !== support.y) signal.y = current.y - 18;
  }
  function update(dt) {
    if (!running || paused || finished) return;
    elapsed += dt; const pressure = elapsed >= 45 ? 1.8 : elapsed >= 30 ? 1.35 : elapsed >= 15 ? 1.1 : 1;
    if (elapsed >= nextSpawn) { createSignal(); nextSpawn = elapsed + Math.max(.65, 1.45 / pressure / (speed === 2 ? 1.15 : 1)); }
    if (elapsed >= nextHazard) { spawnHazard(); nextHazard = elapsed + Math.max(2.2, random(3.8, 5.7) / pressure); }
    if (elapsed >= nextCorruption) { spawnCorruption(); nextCorruption = elapsed + Math.max(1.8, random(3.8, 5.8) / pressure / (speed === 2 ? 1.2 : 1)); }
    if (elapsed >= nextPowerup) { spawnPowerup(); nextPowerup = elapsed + random(8, 12); }
    hazards.forEach((hazard) => { if (freezeUntil <= elapsed) { hazard.x += hazard.direction * hazard.speed * dt * (1 + elapsed / 100); if (hazard.x < 100 || hazard.x > 870) hazard.direction *= -1; } hazard.phase += dt * 3; });
    corruption = corruption.filter((zone) => { zone.pulse += dt * 4; return zone.ttl > elapsed; }); bridges = bridges.filter((bridge) => bridge.ttl > elapsed); powerups = powerups.filter((power) => power.ttl > elapsed); signals.forEach((signal) => updateSignal(signal, dt)); signals = signals.filter((signal) => signal.alive);
    particles = particles.filter((particle) => { particle.x += particle.vx * dt; particle.y += particle.vy * dt; particle.vx *= .96; particle.vy *= .96; particle.life -= dt; return particle.life > 0; }); updateHud(); if (elapsed >= 60) finishRun();
  }
  function draw() {
    ctx.clearRect(0, 0, W, H); ctx.fillStyle = "#0b0f14"; ctx.fillRect(0, 0, W, H); ctx.save(); ctx.translate(viewOffset.x, viewOffset.y);
    ctx.strokeStyle = "rgba(244,242,234,.05)"; ctx.lineWidth = 1; for (let x = 0; x <= W; x += 40) { ctx.beginPath(); ctx.moveTo(x, 0); ctx.lineTo(x, H); ctx.stroke(); } for (let y = 0; y <= H; y += 40) { ctx.beginPath(); ctx.moveTo(0, y); ctx.lineTo(W, y); ctx.stroke(); }
    platforms.forEach((platform) => { ctx.fillStyle = "#20262d"; ctx.fillRect(platform.x1, platform.y, platform.x2 - platform.x1, 13); ctx.strokeStyle = "#59636f"; ctx.lineWidth = 2; ctx.strokeRect(platform.x1, platform.y, platform.x2 - platform.x1, 13); });
    bridges.forEach((bridge) => { ctx.fillStyle = "#55e8ff"; ctx.shadowBlur = 18; ctx.shadowColor = "#55e8ff"; ctx.fillRect(bridge.x1, bridge.y, bridge.x2 - bridge.x1, 9); ctx.shadowBlur = 0; });
    exits.forEach((exit) => { ctx.fillStyle = "#c6ff3d"; ctx.shadowBlur = 25; ctx.shadowColor = "#c6ff3d"; ctx.fillRect(exit.x, exit.y - 55, 12, 55); ctx.shadowBlur = 0; ctx.fillStyle = "#c6ff3d"; ctx.font = "700 10px Arial"; ctx.fillText("EXIT", exit.x - 9, exit.y - 65); });
    corruption.forEach((zone) => { const pulse = 1 + Math.sin(zone.pulse) * .15; ctx.save(); ctx.translate(zone.x, zone.y); ctx.scale(pulse, pulse); ctx.fillStyle = "rgba(255,79,104,.2)"; ctx.strokeStyle = "#ff4f68"; ctx.shadowBlur = 16; ctx.shadowColor = "#ff4f68"; ctx.lineWidth = 2; ctx.fillRect(-11, -11, 22, 22); ctx.strokeRect(-11, -11, 22, 22); ctx.restore(); });
    hazards.forEach((hazard) => { ctx.save(); ctx.translate(hazard.x, hazard.y); ctx.fillStyle = "rgba(255,79,104,.2)"; ctx.strokeStyle = "#ff4f68"; ctx.shadowBlur = 16; ctx.shadowColor = "#ff4f68"; ctx.lineWidth = 2; ctx.fillRect(-hazard.radius, -hazard.radius, hazard.radius * 2, hazard.radius * 2); ctx.strokeRect(-hazard.radius, -hazard.radius, hazard.radius * 2, hazard.radius * 2); ctx.restore(); });
    powerups.forEach((power) => { const labels = { clean: "C", freeze: "T", double: "2X", safe: "S", echo: "E" }; ctx.fillStyle = "#55e8ff"; ctx.shadowBlur = 18; ctx.shadowColor = "#55e8ff"; ctx.fillRect(power.x - 12, power.y - 12, 24, 24); ctx.shadowBlur = 0; ctx.fillStyle = "#0b0f14"; ctx.font = "700 9px Arial"; ctx.textAlign = "center"; ctx.fillText(labels[power.type], power.x, power.y + 3); });
    signals.forEach((signal) => { const color = "#c6ff3d"; ctx.save(); ctx.translate(signal.x, signal.y); if (signal.id === selectedSignalId) { ctx.strokeStyle = "#f4f2ea"; ctx.lineWidth = 2; ctx.beginPath(); ctx.arc(0, 0, 21 + Math.sin(signal.phase) * 2, 0, Math.PI * 2); ctx.stroke(); } ctx.scale(signal.direction, 1); ctx.fillStyle = color; ctx.shadowBlur = 14; ctx.shadowColor = color; ctx.beginPath(); ctx.moveTo(0, -13); ctx.lineTo(13, 0); ctx.lineTo(0, 13); ctx.lineTo(-13, 0); ctx.closePath(); ctx.fill(); ctx.shadowBlur = 0; ctx.fillStyle = "#0b0f14"; ctx.font = "700 7px Arial"; ctx.textAlign = "center"; ctx.fillText(signal.type === "carrier" ? "C" : signal.type === "spark" ? "S" : "R", 0, 3); if (signal.pulseUntil > elapsed) { ctx.strokeStyle = "#f4f2ea"; ctx.lineWidth = 2; ctx.strokeRect(-17, -17, 34, 34); } if (signal.shieldUntil > elapsed) { ctx.strokeStyle = "#c6ff3d"; ctx.setLineDash([3, 3]); ctx.strokeRect(-20, -20, 40, 40); } if (signal.blockedUntil > elapsed) { ctx.strokeStyle = "#ff4f68"; ctx.lineWidth = 2; ctx.strokeRect(-23, -23, 46, 46); ctx.fillStyle = "#ff4f68"; ctx.font = "700 8px Arial"; ctx.fillText("B", 0, -25); } if (signal.floaterUntil > elapsed && !signal.grounded) { ctx.strokeStyle = "#55e8ff"; ctx.lineWidth = 1; ctx.beginPath(); ctx.moveTo(-15, -20); ctx.quadraticCurveTo(0, -28, 15, -20); ctx.stroke(); ctx.beginPath(); ctx.moveTo(0, -20); ctx.lineTo(0, -13); ctx.stroke(); } ctx.restore(); });
    particles.forEach((particle) => { ctx.globalAlpha = Math.max(0, particle.life / .8); ctx.fillStyle = particle.color; ctx.fillRect(particle.x, particle.y, particle.size, particle.size); }); ctx.globalAlpha = 1; ctx.fillStyle = "#737a84"; ctx.font = "700 10px Arial"; ctx.textAlign = "left"; ctx.fillText("SPAWN", 24, 32); ctx.fillStyle = "#646a74"; ctx.fillText("WALK THE NETWORK // BRIDGE THE GAPS", 24, H - 24); ctx.restore();
  }
  function collapse() { const overlay = $("signal-collapse"); overlay.innerHTML = "<span>WARNING</span><small>SIGNAL UNSTABLE</small>"; overlay.classList.add("show"); window.setTimeout(() => { overlay.innerHTML = "<span>CORRUPTION SPREADING</span><small>CRITICAL</small>"; }, 260); window.setTimeout(() => { overlay.innerHTML = "<span>SIGNAL LOST</span>"; }, 550); }
  async function finishRun() {
    if (!running || finished) return; finished = true; running = false; paused = false; signals.filter((signal) => signal.alive).forEach((signal) => lose(signal, "The signal collapsed before this Signal reached the exit.")); const previousBest = Number(localStorage.getItem(bestKey) || 0); const newBest = score > previousBest; if (newBest) localStorage.setItem(bestKey, String(score)); const stats = localStats(); stats.runs += 1; stats.saved += saved; stats.bestCombo = Math.max(stats.bestCombo, bestCombo); if (lost === 0 && saved > 0) stats.perfect += 1; localStorage.setItem(statsKey, JSON.stringify(stats)); if (saved) achievement("FIRST SIGNAL"); if (lost === 0 && saved) achievement("CLEAN RUN"); if (bestCombo >= 10) achievement("OVERCLOCKED"); if (previousBest > 0 && score >= previousBest * 1.25) achievement("GANK THE SCORE"); lastRun = { score: Math.round(score), saved, lost, bestCombo, fastestRescueMs: fastestRescue === null ? 0 : Math.round(fastestRescue * 1000), highestPhase: 3, runSeconds: 60, xpEarned: Math.min(250, Math.max(10, Math.round(score / 100))), achievements: JSON.parse(localStorage.getItem(achievementsKey) || "[]"), submitted: false }; collapse(); window.setTimeout(() => showResult(newBest), 850);
  }
  function showResult(newBest) { $("signal-message").hidden = false; $("signal-message").innerHTML = "<strong>SIGNAL LOST</strong><span>Save the swarm. Gank the score. Run it again.</span>"; $("swarm-start").hidden = false; $("swarm-start").innerHTML = "Run again <span>&rarr;</span>"; $("swarm-pause").hidden = true; $("swarm-restart").hidden = true; $("swarm-result").hidden = false; $("result-score").textContent = format(lastRun.score); $("result-saved").textContent = lastRun.saved; $("result-lost").textContent = lastRun.lost; $("result-combo").textContent = `x${lastRun.bestCombo}`; $("result-fastest").textContent = lastRun.fastestRescueMs ? `${(lastRun.fastestRescueMs / 1000).toFixed(2)}s` : "--"; $("result-mark").textContent = newBest ? "NEW RECORD" : "SIGNAL LOST"; $("result-record").textContent = newBest ? "New personal best. The network wants another run." : "The signal collapsed. Your best run is still beatable."; $("swarm-status").textContent = newBest ? `New personal best: ${format(lastRun.score)}.` : `Best score on this device: ${format(Math.max(Number(localStorage.getItem(bestKey) || 0), lastRun.score))}.`; $("signal-collapse").classList.remove("show"); updateHud(); submitScore(); }
  async function loadLeaderboard() { const body = $("swarm-leaderboard-body"); if (!client) { body.innerHTML = '<tr><td colspan="5">Global scores need the XP backend connection.</td></tr>'; return; } const result = await client.from("signal_swarm_leaderboard").select("display_name,best_score,best_saved,best_combo").order("best_score", { ascending: false }).limit(25); if (result.error) { body.innerHTML = '<tr><td colspan="5">Run the Signal Swarm migration to enable global scores.</td></tr>'; return; } body.innerHTML = result.data?.length ? result.data.map((row, index) => `<tr><td>${index + 1}</td><td>${escapeHtml(row.display_name || "GankByte Player")}</td><td>${format(row.best_score)}</td><td>${row.best_saved}</td><td>x${row.best_combo}</td></tr>`).join("") : '<tr><td colspan="5">No approved runs yet. Be the first to save the swarm.</td></tr>'; }
  async function submitScore() { if (!client || !user || !lastRun || lastRun.submitted) return; const result = await client.from("signal_swarm_scores").insert({ user_id: user.id, score: lastRun.score, signals_saved: lastRun.saved, signals_lost: lastRun.lost, best_combo: lastRun.bestCombo, fastest_rescue_ms: lastRun.fastestRescueMs, highest_phase: lastRun.highestPhase, run_seconds: lastRun.runSeconds, xp_earned: lastRun.xpEarned, achievements: lastRun.achievements, status: "approved" }); if (result.error) { $("swarm-auth-status").textContent = "Run complete, but the online score could not be saved."; return; } lastRun.submitted = true; $("swarm-auth-status").textContent = "Score posted. XP and profile history updated."; await loadLeaderboard(); const rank = await client.from("signal_swarm_leaderboard").select("id,best_score").order("best_score", { ascending: false }).limit(500); if (!rank.error && user) { const position = (rank.data || []).findIndex((row) => row.id === user.id); $("result-rank").textContent = position >= 0 ? `#${position + 1}` : "Saved"; } }
  async function loadSession(session) { user = session?.user || null; if (!user) { $("swarm-auth-status").textContent = "Sign in with Discord to submit scores."; $("swarm-login").hidden = false; $("swarm-logout").hidden = true; return; } const name = user.user_metadata?.global_name || user.user_metadata?.full_name || "Discord player"; $("swarm-auth-status").textContent = `Signed in as ${name}. Completed runs save automatically.`; $("swarm-login").hidden = true; $("swarm-logout").hidden = false; await submitScore(); }
  async function initOnline() { if (!config.supabaseUrl || !config.supabasePublishableKey || !window.supabase) { $("swarm-login").disabled = true; $("swarm-auth-status").textContent = "Local play is ready. Online scores are unavailable."; return; } client = window.supabase.createClient(config.supabaseUrl, config.supabasePublishableKey); client.auth.onAuthStateChange((event, session) => window.setTimeout(() => loadSession(session), 0)); const session = await client.auth.getSession(); await loadSession(session.data.session); await loadLeaderboard(); }
  function startRun() { resetRun(); running = true; $("signal-message").hidden = true; $("swarm-start").hidden = true; $("swarm-pause").hidden = false; $("swarm-restart").hidden = false; $("swarm-status").textContent = "Signals are moving. Build a route, save the swarm, and push the speed when ready."; canvas.focus(); }
  function chooseAbility(name) { selectedAbility = name; document.querySelectorAll(".signal-ability").forEach((button) => button.classList.toggle("is-selected", button.dataset.ability === name)); $("swarm-status").textContent = `${abilityNames[name]} selected. Click a Signal or a gap on the network.`; }
  function frame(timestamp) { const dt = Math.min(.05, (timestamp - lastFrame) / 1000 || 0); lastFrame = timestamp; update(dt); draw(); window.requestAnimationFrame(frame); }
  document.querySelectorAll(".signal-ability").forEach((button) => { button.addEventListener("click", () => chooseAbility(button.dataset.ability)); button.addEventListener("pointerdown", () => { button.dataset.holdTimer = String(window.setTimeout(() => { $("swarm-status").textContent = `${abilityNames[button.dataset.ability]} preview: target an individual Signal or network platform.`; }, 500)); }); button.addEventListener("pointerup", () => window.clearTimeout(Number(button.dataset.holdTimer || 0))); });
  canvas.addEventListener("pointerdown", (event) => { if (!running || paused) return; event.preventDefault(); pointerStart = { x: event.clientX, y: event.clientY, pointerType: event.pointerType }; pointerMoved = false; canvas.setPointerCapture?.(event.pointerId); });
  canvas.addEventListener("pointermove", (event) => { if (!pointerStart || pointerStart.pointerType !== "touch" || !event.buttons) return; const dx = event.clientX - pointerStart.x, dy = event.clientY - pointerStart.y; if (Math.hypot(dx, dy) < 7) return; pointerMoved = true; viewOffset.x = clamp(viewOffset.x + dx * W / canvas.clientWidth, -100, 100); viewOffset.y = clamp(viewOffset.y + dy * H / canvas.clientHeight, -55, 55); pointerStart = { x: event.clientX, y: event.clientY, pointerType: "touch" }; canvas.classList.add("dragging"); });
  canvas.addEventListener("pointerup", (event) => { if (!pointerStart) return; if (!pointerMoved) { target = boardPoint(event); useAbility(selectedAbility, target); } pointerStart = null; pointerMoved = false; canvas.classList.remove("dragging"); }); canvas.addEventListener("pointercancel", () => { pointerStart = null; pointerMoved = false; canvas.classList.remove("dragging"); });
  $("swarm-speed").addEventListener("input", (event) => { speed = Number(event.target.value); updateHud(); if (running) $("swarm-status").textContent = `${speedNames[speed]} speed selected. ${speed === 2 ? "Corruption and pressure rise faster." : ""}`; });
  $("swarm-start").addEventListener("click", startRun); $("swarm-run-again").addEventListener("click", startRun); $("swarm-restart").addEventListener("click", startRun); $("swarm-pause").addEventListener("click", () => { paused = !paused; $("swarm-pause").innerHTML = paused ? "Resume <span>&rarr;</span>" : "Pause <span>&#10074;&#10074;</span>"; $("swarm-status").textContent = paused ? "Run paused." : "Run resumed."; }); $("swarm-help").addEventListener("click", () => $("swarm-help-dialog").showModal()); $("swarm-help-close").addEventListener("click", () => $("swarm-help-dialog").close()); $("swarm-help-dialog").addEventListener("click", (event) => { if (event.target === $("swarm-help-dialog")) $("swarm-help-dialog").close(); });
  $("swarm-login").addEventListener("click", async () => { if (client) await client.auth.signInWithOAuth({ provider: "discord", options: { redirectTo: window.location.href.split("#")[0] } }); }); $("swarm-logout").addEventListener("click", async () => { if (client) await client.auth.signOut(); });
  window.addEventListener("keydown", (event) => { const key = event.key.toLowerCase(); if (["1", "2", "3", "4", "5", "6", "7"].includes(key)) { chooseAbility(["redirect", "bridge", "cleanse", "pulse", "recall", "blocker", "floater"][Number(key) - 1]); return; } if (event.code === "Space") { event.preventDefault(); if (running && !paused) useAbility(selectedAbility, target); } if (event.key === "Escape" && running) $("swarm-pause").click(); if (key === "r" && running) startRun(); });
  resetRun(); initOnline().catch(() => { $("swarm-auth-status").textContent = "Local play is ready. Online scores are unavailable."; }); window.requestAnimationFrame(frame);
})();
