(() => {
  "use strict";
  const $ = (id) => document.getElementById(id), form = $("sql-form"), output = $("sql-output"), notes = $("sql-notes"), status = $("sql-status");
  const val = (id) => $(id).value.trim(), safeIdentifier = (value) => /^[A-Za-z_][A-Za-z0-9_.]*$/.test(value), list = (value) => value.split(",").map((item) => item.trim()).filter(Boolean);
  let current = "Choose an operation and build a query.";
  function sync() { const op = val("sql-operation"); $("sql-columns-wrap").hidden = ["delete","create"].includes(op); $("sql-values-wrap").hidden = !["insert"].includes(op); $("sql-set-wrap").hidden = !["update"].includes(op); $("sql-join-wrap").hidden = !["select"].includes(op); $("sql-order").closest("div").hidden = !["select","delete"].includes(op); $("sql-limit").closest("div").hidden = !["select"].includes(op); }
  function build() { const op = val("sql-operation"), table = val("sql-table"), columns = list(val("sql-columns")), dialect = val("sql-dialect"); if (!safeIdentifier(table)) throw Error("Use a simple table identifier such as public.users or users."); if (columns.some((item) => !safeIdentifier(item) && item !== "*")) throw Error("Columns may contain letters, numbers, underscores, dots, or * only."); const where = val("sql-where"), join = val("sql-join"), order = val("sql-order"), limit = val("sql-limit"); let query = ""; if (op === "select") { query = `SELECT ${columns.join(", ") || "*"}\nFROM ${table}`; if (join) query += `\nJOIN ${join}`; if (where) query += `\nWHERE ${where}`; if (order) query += `\nORDER BY ${order}`; if (limit) query += `\nLIMIT ${limit}`; } else if (op === "insert") { query = `INSERT INTO ${table} (${columns.join(", ") || "columns"})\nVALUES (${val("sql-values") || "values"});`; } else if (op === "update") { query = `UPDATE ${table}\nSET ${val("sql-set") || "column = value"}`; if (where) query += `\nWHERE ${where}`; query += ";"; } else if (op === "delete") { query = `DELETE FROM ${table}`; if (where) query += `\nWHERE ${where}`; query += ";"; } else { const body = columns.length ? columns.map((item) => `    ${item}`).join(",\n") : "    id INTEGER PRIMARY KEY"; query = dialect === "postgresql" ? `CREATE TABLE IF NOT EXISTS public.${table} (\n${body}\n);` : `CREATE TABLE IF NOT EXISTS ${table} (\n${body}\n);`; } return query.replace(/\n{3,}/g,"\n\n"); }
  function renderNotes() { const op = val("sql-operation"), where = val("sql-where"), query = current; const items = []; if (["update","delete"].includes(op) && !where) items.push(["warn", "No WHERE clause: this statement can affect every row."]); if (op === "insert" && !val("sql-values")) items.push(["warn", "Values are still a placeholder; add values that match the selected columns."]); if (val("sql-limit") && !/^\d+$/.test(val("sql-limit"))) items.push(["error", "LIMIT should be a whole number."]); if (query.includes("public.") && val("sql-dialect") !== "postgresql") items.push(["warn", "The public schema prefix is normally PostgreSQL-specific."]); if (!items.length) items.push(["good", "No obvious builder warnings. Review the generated SQL before executing it."]); notes.replaceChildren(...items.map(([kind, text]) => { const li = document.createElement("li"); li.className = kind; li.textContent = text; return li; })); }
  form.addEventListener("submit", (event) => { event.preventDefault(); try { current = build(); output.textContent = current; renderNotes(); status.textContent = "Query built locally."; status.classList.remove("is-error"); } catch (error) { status.textContent = error.message; status.classList.add("is-error"); } });
  $("sql-operation").addEventListener("change", sync); $("format-sql").addEventListener("click", () => { current = current.replace(/\s*,\s*/g, ",\n    ").replace(/\s+(FROM|JOIN|WHERE|ORDER BY|GROUP BY|LIMIT|SET|VALUES)\s+/g, "\n$1 "); output.textContent = current; status.textContent = "SQL formatted locally."; });
  $("clear-sql").addEventListener("click", () => { $("sql-where").value = ""; $("sql-join").value = ""; $("sql-order").value = ""; $("sql-limit").value = ""; current = "Choose an operation and build a query."; output.textContent = current; notes.innerHTML = "<li>Warnings will appear here after the query is built.</li>"; status.textContent = "Query cleared."; });
  $("copy-sql").addEventListener("click", async () => { try { await navigator.clipboard.writeText(current); status.textContent = "SQL copied to the clipboard."; } catch { status.textContent = "Clipboard access was unavailable."; status.classList.add("is-error"); } });
  $("download-sql").addEventListener("click", () => { const url = URL.createObjectURL(new Blob([current], {type:"text/sql;charset=utf-8"})); const link = document.createElement("a"); link.href = url; link.download = `${val("sql-table") || "query"}.sql`; link.click(); URL.revokeObjectURL(url); status.textContent = "SQL file downloaded."; });
  sync();
})();
